services:
    rmcgirr83.activity24hours.listener:
        class: rmcgirr83\activity24hours\event\listener
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @template
            - @user
        tags:
            - { name: event.listener }
