services:
    rmcgirr83.upcomingbirthdays.acplistener:
        class: rmcgirr83\upcomingbirthdays\event\acp_listener
        tags:
            - { name: event.listener }

    rmcgirr83.upcomingbirthdays.mainlistener:
        class: rmcgirr83\upcomingbirthdays\event\main_listener
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @template
            - @user 
        tags:
            - { name: event.listener }
