sdd_wgrywajka_controller:
    pattern: /wgrywajka/proste
    defaults: { _controller: sdd.wgrywajka.controller:proste }

sdd_wgrywajka_zaawansowane:
    pattern: /wgrywajka/zaawansowane
    defaults: { _controller: sdd.wgrywajka.controller:zaawansowane }

sdd_wgrywajka_wynik:
    pattern: /wgrywajka/wynik
    defaults: { _controller: sdd.wgrywajka.controller:wynik }

sdd_wgrywajka_mojepliki:
    pattern: /wgrywajka/mojepliki
    defaults: { _controller: sdd.wgrywajka.controller:mojepliki }

sdd_wgrywajka_szukaj_pliki_usera:
    pattern: /wgrywajka/user
    defaults: { _controller: sdd.wgrywajka.controller:szukaj_pliki_usera }

sdd_wgrywajka_szukaj_posty_z_plikiem:
    pattern: /wgrywajka/plik
    defaults: { _controller: sdd.wgrywajka.controller:szukaj_posty_z_plikiem }

sdd_wgrywajka_szukaj:
    pattern: /wgrywajka/szukaj
    defaults: { _controller: sdd.wgrywajka.controller:szukaj }

sdd_wgrywajka_kod:
    pattern: /wgrywajka/kod
    defaults: { _controller: sdd.wgrywajka.controller:kod }

sdd_wgrywajka_prywatny:
    pattern: /wgrywajka/prywatny
    defaults: { _controller: sdd.wgrywajka.controller:prywatny }

sdd_wgrywajka_usun:
    pattern: /wgrywajka/usun
    defaults: { _controller: sdd.wgrywajka.controller:usun }
    
sdd_wgrywajka_admin:
    pattern: /wgrywajka/admin
    defaults: { _controller: sdd.wgrywajka.controller:admin }

sdd_wgrywajka_adminzarzadzaj:
    pattern: /wgrywajka/adminzarzadzaj
    defaults: { _controller: sdd.wgrywajka.controller:adminzarzadzaj }