sdd_wgrywajka_controller:
    pattern: /wgrywajka/proste
    defaults: { _controller: sdd.wgrywajka.controller:proste }

sdd_wgrywajka_zaawansowane:
    pattern: /wgrywajka/zaawansowane
    defaults: { _controller: sdd.wgrywajka.controller:zaawansowane }

sdd_wgrywajka_wynik:
    pattern: /wgrywajka/wynik
    defaults: { _controller: sdd.wgrywajka.controller:wynik }

sdd_wgrywajka_mojepliki:
    pattern: /wgrywajka/mojepliki
    defaults: { _controller: sdd.wgrywajka.controller:mojepliki }
#    defaults: { _controller: sdd.wgrywajka.controller:mojepliki, start: 0 }
#    requirements:
#        start: \d*
    
sdd_wgrywajka_szukaj:
    pattern: /wgrywajka/szukaj
    defaults: { _controller: sdd.wgrywajka.controller:szukaj }