imports:
    - { resource: parameters.yml }

services:
    sdd.wgrywajka.controller:
        class: sdd\wgrywajka\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'
            - '@request'
            - '@dbal.conn'
            - '@auth'